pipeline:
  build:
    when:
      event: [tag, push, pull_request]
    image: node:${NODE_VERSION}      
    commands:
      - npm install

  test:
    when:
      event: [tag, push, pull_request]
    image: node:${NODE_VERSION}
    commands:
      - npm test

  analysis:
    when:
      status: success
      matrix:
        NODE_VERSION: 6
    image: node:${NODE_VERSION}
    environment:
      - COVERALLS_SERVICE_NAME=${CI}
      - COVERALLS_SERVICE_JOB_ID=${DRONE_JOB_NUMBER}
      - COVERALLS_GIT_COMMIT=${DRONE_GIT_COMMIT_SHA}
    commands:
      - npm install -g coveralls
      - npm run coveralls

  publish:
    when:
      status: success
      event: tag
    commands:
      - npm run compile
    
matrix:
  NODE_VERSION:
    - 6
    - 7
